config/routes.rb
Rails.application.routes.draw do
  root "scores#index"

  resources :scores
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/score.rb
class Score < ApplicationRecord
  validates :team_one, presence: true
  validates :team_two, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/scores_controller.rb
class ScoresController < ApplicationController
  def index
    @scores = Score.all
  end


  def show
    @score = Score.find(params[:id])
  end


  def new
    @score = Score.new
  end


  def create
    @score = Score.new(score_params)

    if @score.save
      redirect_to @score
    else
      render :new
    end
  end


  def edit
    @score = Score.find(params[:id])
  end


  def update
    @score = Score.find(params[:id])

    if @score.update(score_params)
      redirect_to @score
    else
      render :edit
    end
  end


  def destroy
    @score = Score.find(params[:id])
    @score.destroy

    redirect_to root_path
  end


  private
    def score_params
      params.require(:score).permit(:team_one, :team_two, :round_number, :game_number)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/scores_helper.rb
module ScoresHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AutoBags</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/scores/_form.html.erb
<h1>Enter a Score</h1>

<%= form_with model: score do |form| %>
  <div>
    <%= form.label :team_one %><br>
    <%= form.text_field :team_one %>
    <% score.errors.full_messages_for(:team_one).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <br>

  <div>
    <%= form.label :team_two %><br>
    <%= form.text_field :team_two %>
    <% score.errors.full_messages_for(:team_two).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <br>

  <div>
    <%= form.label :round_number %><br>
    <%= form.text_field :round_number %>
    <% score.errors.full_messages_for(:round_number).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <br>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/scores/edit.html.erb
<h1>Edit the Score</h1>

<%= render "form", score: @score %>

app/views/scores/index.html.erb
<h1>Game Scores</h1>

<ul>
  <% @scores.each do |score| %>

    <li>
      <h4>Round Number: <%= link_to score.round_number, score %></h4>

      <h5>&emsp;&emsp;Team One Score: 
      <%= score.team_one %>
      </h5>

      <h5>&emsp;&emsp;Team Two Score: 
      <%= score.team_two %>
      </h5>
    </li>
  <% end %>
</ul>

<%= link_to "Create a Score??", new_score_path %>

app/views/scores/new.html.erb
<h1>Enter a New Score</h1>

<%= render "form", score: @score %>

app/views/scores/show.html.erb
<h1>Game Number: <%= @score.game_number %></h1>
<p>Round Number: <%= @score.round_number %></p>
<p>Team One Score: <%= @score.team_one %></p>
<p>Team Two Score: <%= @score.team_two %></p>

<ul>
  <li><%= link_to "Edit", edit_score_path(@score) %></li>
  <li><%= link_to "Destroy", score_path(@score),
    method: :delete,
    data: { confirm: "Are you sure?" } %></li>
<ul>